aix change from downloadSourceTarballAIX -> checkoutUsingGitWorktree
AIX is out of space. checkoutUsingGitWorktree offers better space
management.

rlimits for memory do need to be raised otherwise:

Preparing worktree (new branch '10.2')
Branch '10.2' set up to track remote branch '10.2' from 'origin'.
error: Out of memory, malloc failed (tried to allocate 31003242 bytes)
fatal: packed object 55c43c5fb953f9c91975c394a3163f27da782db1 (stored in /home/buildbot/packages/mariadb-server/.git/objects/pack/pack-22ed67ad585a042cb03c1aa1206a53ba6cc5c51a.pack) is corrupt